[package]
description = "Declarative secrets, every environment, any provider"
edition.workspace = true
license = "Apache-2.0"
name = "secretspec"
repository = "https://github.com/cachix/secretspec"
version.workspace = true

[lib]
name = "secretspec"
path = "src/lib.rs"

[[bin]]
name = "secretspec"
path = "src/bin/secretspec.rs"
required-features = ["cli"]

[[test]]
name = "integration"
path = "../tests/lib.rs"
required-features = ["aws"]

[dependencies]
aws-config = { workspace = true, optional = true }
aws-sdk-secretsmanager = { workspace = true, optional = true }
clap.workspace = true
colored.workspace = true
data-encoding.workspace = true
dotenvy.workspace = true
etcetera.workspace = true
google-cloud-secretmanager-v1 = { workspace = true, optional = true }
inquire.workspace = true
keyring = { workspace = true, optional = true }
linkme.workspace = true
miette.workspace = true
once_cell.workspace = true
rand.workspace = true
secrecy.workspace = true
serde.workspace = true
serde-envfile.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, optional = true }
toml.workspace = true
url.workspace = true
uuid.workspace = true
whoami = { workspace = true, optional = true }

[dev-dependencies]
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
tokio = { version = "1", features = ["macros", "rt"] }

[features]
aws = ["dep:aws-config", "dep:aws-sdk-secretsmanager", "dep:tokio"]
cli = []
default = ["cli", "keyring"]
gcsm = ["dep:google-cloud-secretmanager-v1", "dep:tokio"]
keyring = ["dep:keyring", "dep:whoami"]
